[project]
name = "kaleido"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "textual>=7.4.0",
    "textual-dev>=1.8.0",
]
